/**
 * @file STLWriter.cpp
 * @brief STL file writer (binary and ASCII)
 */

#include "geom-core/cad/Types.hpp"
#include <fstream>
#include <cstring>
#include <cmath>

namespace madfam::geom::io {

using namespace madfam::geom::cad;

namespace {

// Compute face normal from triangle vertices
void computeFaceNormal(const float* v0, const float* v1, const float* v2,
                        float& nx, float& ny, float& nz) {
    // Edge vectors
    float e1x = v1[0] - v0[0];
    float e1y = v1[1] - v0[1];
    float e1z = v1[2] - v0[2];

    float e2x = v2[0] - v0[0];
    float e2y = v2[1] - v0[1];
    float e2z = v2[2] - v0[2];

    // Cross product
    nx = e1y * e2z - e1z * e2y;
    ny = e1z * e2x - e1x * e2z;
    nz = e1x * e2y - e1y * e2x;

    // Normalize
    float len = std::sqrt(nx * nx + ny * ny + nz * nz);
    if (len > 1e-10f) {
        nx /= len;
        ny /= len;
        nz /= len;
    }
}

}  // namespace

/**
 * @brief Write mesh to binary STL file
 */
Result<bool> writeSTL(const MeshData& mesh, const std::string& filepath, bool binary) {
    if (binary) {
        std::ofstream file(filepath, std::ios::binary);
        if (!file.is_open()) {
            return Result<bool>::fail("IO_ERROR", "Failed to create file: " + filepath);
        }

        // Header (80 bytes)
        char header[80] = {};
        strncpy(header, "Binary STL generated by geom-core", 79);
        file.write(header, 80);

        // Triangle count
        uint32_t numTriangles = mesh.triangleCount;
        file.write(reinterpret_cast<const char*>(&numTriangles), 4);

        // Write triangles
        for (uint32_t i = 0; i < mesh.triangleCount; ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[i0 * 3];
            const float* v1 = &mesh.positions[i1 * 3];
            const float* v2 = &mesh.positions[i2 * 3];

            // Compute face normal
            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            // Write normal
            file.write(reinterpret_cast<const char*>(&nx), 4);
            file.write(reinterpret_cast<const char*>(&ny), 4);
            file.write(reinterpret_cast<const char*>(&nz), 4);

            // Write vertices
            file.write(reinterpret_cast<const char*>(v0), 12);
            file.write(reinterpret_cast<const char*>(v1), 12);
            file.write(reinterpret_cast<const char*>(v2), 12);

            // Attribute byte count
            uint16_t attr = 0;
            file.write(reinterpret_cast<const char*>(&attr), 2);
        }

        return Result<bool>::ok(true);
    } else {
        // ASCII STL
        std::ofstream file(filepath);
        if (!file.is_open()) {
            return Result<bool>::fail("IO_ERROR", "Failed to create file: " + filepath);
        }

        file << "solid geom-core\n";

        for (uint32_t i = 0; i < mesh.triangleCount; ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[i0 * 3];
            const float* v1 = &mesh.positions[i1 * 3];
            const float* v2 = &mesh.positions[i2 * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            file << "  facet normal " << nx << " " << ny << " " << nz << "\n";
            file << "    outer loop\n";
            file << "      vertex " << v0[0] << " " << v0[1] << " " << v0[2] << "\n";
            file << "      vertex " << v1[0] << " " << v1[1] << " " << v1[2] << "\n";
            file << "      vertex " << v2[0] << " " << v2[1] << " " << v2[2] << "\n";
            file << "    endloop\n";
            file << "  endfacet\n";
        }

        file << "endsolid geom-core\n";

        return Result<bool>::ok(true);
    }
}

/**
 * @brief Write mesh to STL in memory buffer
 */
Result<std::vector<uint8_t>> writeSTLToMemory(const MeshData& mesh, bool binary) {
    std::vector<uint8_t> buffer;

    if (binary) {
        // Calculate size: 80 header + 4 count + 50 per triangle
        size_t size = 84 + mesh.triangleCount * 50;
        buffer.resize(size);

        uint8_t* ptr = buffer.data();

        // Header
        memset(ptr, 0, 80);
        strncpy(reinterpret_cast<char*>(ptr), "Binary STL generated by geom-core", 79);
        ptr += 80;

        // Triangle count
        memcpy(ptr, &mesh.triangleCount, 4);
        ptr += 4;

        // Triangles
        for (uint32_t i = 0; i < mesh.triangleCount; ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[i0 * 3];
            const float* v1 = &mesh.positions[i1 * 3];
            const float* v2 = &mesh.positions[i2 * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            memcpy(ptr, &nx, 4); ptr += 4;
            memcpy(ptr, &ny, 4); ptr += 4;
            memcpy(ptr, &nz, 4); ptr += 4;

            memcpy(ptr, v0, 12); ptr += 12;
            memcpy(ptr, v1, 12); ptr += 12;
            memcpy(ptr, v2, 12); ptr += 12;

            uint16_t attr = 0;
            memcpy(ptr, &attr, 2); ptr += 2;
        }
    } else {
        // ASCII - use string stream
        std::ostringstream ss;
        ss << "solid geom-core\n";

        for (uint32_t i = 0; i < mesh.triangleCount; ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[i0 * 3];
            const float* v1 = &mesh.positions[i1 * 3];
            const float* v2 = &mesh.positions[i2 * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            ss << "  facet normal " << nx << " " << ny << " " << nz << "\n";
            ss << "    outer loop\n";
            ss << "      vertex " << v0[0] << " " << v0[1] << " " << v0[2] << "\n";
            ss << "      vertex " << v1[0] << " " << v1[1] << " " << v1[2] << "\n";
            ss << "      vertex " << v2[0] << " " << v2[1] << " " << v2[2] << "\n";
            ss << "    endloop\n";
            ss << "  endfacet\n";
        }

        ss << "endsolid geom-core\n";

        std::string str = ss.str();
        buffer.assign(str.begin(), str.end());
    }

    return Result<std::vector<uint8_t>>::ok(std::move(buffer));
}

}  // namespace madfam::geom::io
